# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: docker-image-tag-bot

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      REPOSITORY: 677979501910.dkr.ecr.ap-northeast-2.amazonaws.com

    steps:
      - uses: actions/checkout@v3
      - name: Install Kustomize
        run: |
          wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
          sudo tar -xvf kustomize.tar.gz -C /usr/local/bin/
      - name: set up Python
        uses: actions/setup-python@v3
        with:
          python_version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: get merge commit's short-sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create Pull Request
        run: python ./.github/workflows/edit_image_and_create_pr.py ${{ secrets.TOKEN }} "$REPOSITORY" ${{ steps.vars.outputs.sha_short }} ${{ github.event.number }}
